url=jdbc:postgresql://localhost:5432/dealsafe?currentSchema=public
username=postgres
password=postgres
driver=org.postgresql.Driver

defaultSchemaName=public
referenceSchemaName=public

referenceUrl=hibernate:spring:org.gfinnovation?dialect=org.hibernate.dialect.PostgreSQLDialect&hibernate.default_schema=public&hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
outputChangeLogFile=src/main/resources/db/changelog/db.changelog-baseline.xml
diffChangeLogFile=src/main/resources/db/changelog/db.changelog-new-migration.xml
hibernate.dialect=org.postgresql.Driver

verbose=true
logging=debug