server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: Dealsafe-Dev
  datasource:
    url: jdbc:postgresql://localhost:5432/dealsafe?useSSL=false
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  neo4j:
    uri: neo4j://localhost:7999
    authentication:
      username: neo4j
      password: password
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: dealsafe_logs
      username: mongoadmin
      password: secret
      authentication-database: admin

jwt:
  publicKey: ${JWT_PUBLIC_KEY}
  privateKey: ${JWT_PRIVATE_KEY}