server:
  port: 8080
  servlet:
    context-path: /api
  ssl:
    enabled: false

spring:
  application:
    name: Dealsafe-Test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: false