server:
  port: 8080
  servlet:
    context-path: /api
  ssl:
    enabled: false

spring:
  application:
    name: Dealsafe-Test
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml